#include "stdio.h"
#include "stdlib.h"

/*
    ESTE ARCHIVO ES EL ARCHIVO DE CABEZERA ASICIADO A TAD.c
    PRIMERO DEFINIMOS LAS PRIMITIVAS DE LAS FUNCIONES QUE VAMOS A UTILIZAR EN EL ARCHIVO
    TAD.c.

*/
//EL TYPEDEF SE USA PARA QUE CUANDO TENGAMOS QUE DEFINIR VARIABLES, SOLO TENGAMOS
//QUE PONER pasajero var; Y QUE NO SEA NECESARIO POENR EL struct
typedef struct pasajero
{
	/*
		AHORA TENEMOS QUE DEFINIR QUE DATOS SER ALMACENARAN DE CADA PASAJERO
		EN NUESTRO CASO COMO NO NOS DICEN NADA EN EL ENUNCIADO, ALMACENAREMOS
		NOMBRE, APELLIDOS, DESTINO Y ESTADO DEL PAGO(bool)
	*/
	char nombre[20];
	char apellido1[20];
	char apellido2[20];
	char destino[6];
	int statusPago;
    struct pasajeros *sigPasajero;
	struct pasajeros *antPasajero;
/*
	AL TENER DOS PUNTEROS, UNO AL PASAJERO SIGUIENTE Y OTRO AL PASAJERO ANTERIOR
	ESTAMOS INDICANDO QUE LAS LISTAS SERAN DOBLEMENTE ENLAZADA, PARA PODER RECORRERLAS
	EN AMBOS SENTIDOS, LO QUE NOS DARA UN RENDIMIENTO MAS OPTIMO, POR QUE NO ES NECESARIO
	VOLVER A EMPEZAR CUANDO ESTEMOS BUSCANDO UN PASAJERO, SIMPLEMENTE MOVERSE ADELANTE
	O ATRÁS.
*/
} pasajeros;

